package dev.scarlet.logger

/**
 * A JVM-friendly static logging facade that delegates all calls to [Logger.default].
 *
 * This object provides a set of `@JvmStatic` utility methods, allowing Java code to
 * invoke logging functions without referencing Kotlin's companion objects or top-level
 * declarations. All methods mirror the interface of [Logger] but are exposed as plain
 * static methods in the generated bytecode (e.g., `DefaultLogger.d(...)` in Java).
 *
 * It is intended for use in mixed Kotlin-Java projects where a simple, familiar logging
 * API is preferred over direct access to the [Logger] instance.
 *
 * Example (Java):
 * ```java
 * DefaultLogger.d("MainActivity", "User clicked button");
 * DefaultLogger.e("Network", "Failed to load data", exception);
 * ```
 *
 * > **Note**: This class does not implement any logging logic itself—it merely forwards
 * > calls to the current [Logger.default] instance. To customize behavior (e.g., log level,
 * > output format, or destination), configure [Logger.default] or replace it with a custom
 * > [Logger] implementation.
 *
 * @author Scarlet Pan
 * @since 1.0.0
 */
object DefaultLogger {

    /**
     * Logs a message at the DEBUG level.
     *
     * Typically used for detailed diagnostic information during development.
     * Whether the message is output depends on the specific implementation.
     *
     * @param tag A short string identifying the source of the log message.
     * @param msg The log message (non-null).
     * @param tr An optional throwable; if provided, the implementation should format and append its stack trace.
     */
    @JvmOverloads
    @JvmStatic
    fun d(tag: String, msg: String, tr: Throwable? = null) = Logger.default.d(tag, msg, tr)


    /**
     * Logs a message at the INFO level.
     *
     * Used for general operational status, key workflow steps, etc.
     *
     * @param tag The log tag.
     * @param msg The log message.
     * @param tr An optional throwable.
     */
    @JvmOverloads
    @JvmStatic
    fun i(tag: String, msg: String, tr: Throwable? = null) = Logger.default.i(tag, msg, tr)

    /**
     * Logs a WARN-level message with only a throwable (no explicit message).
     *
     * Equivalent to calling `w(tag, "", tr)`. Useful when only an exception needs to be logged.
     *
     * @param tag The log tag.
     * @param tr The throwable (must be non-null).
     */
    @JvmStatic
    fun w(tag: String, tr: Throwable) = Logger.default.w(tag, tr)

    /**
     * Logs a message at the WARN level.
     *
     * Indicates potential issues or unexpected states that do not prevent continued execution.
     *
     * @param tag The log tag.
     * @param msg The warning message (may be an empty string).
     * @param tr An optional throwable.
     */
    @JvmOverloads
    @JvmStatic
    fun w(tag: String, msg: String, tr: Throwable? = null) = Logger.default.w(tag, msg, tr)

    /**
     * Logs a message at the ERROR level.
     *
     * Indicates serious failures or exceptions that may impact functionality.
     * It is strongly recommended to pass [tr] when catching exceptions to preserve full context.
     *
     * @param tag The log tag.
     * @param msg The error description.
     * @param tr An optional throwable (recommended to provide).
     */
    @JvmOverloads
    @JvmStatic
    fun e(tag: String, msg: String, tr: Throwable? = null) = Logger.default.e(tag, msg, tr)

}